### ISSUE TITLE
Game Pad Bindings

### ISSUE THREAD

**Issue by msolis488** [amwatson/CitraVR#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

First Release

### Description of Issue

Trying to change the Game Pad settings doesn't seem to do anything. When it comes to the buttons, I can only input B or Y on my Quest Controllers. When I do the input, it comes up as 'Virtual Button 4' for both B and Y.

### Expected Behavior

To be able to map bindings for Quest controller

### Reproduction Steps

Go to settings in Citra VR and go through the process of setting up game pad bindings.

### Log File

How would I get the log file from the APK in Quest?

### System Configuration

Quest 3

**Comment by amwatson** [comment]
It's a hidden Quest setting. Press 'select' + 'start' on the gamepad

**Comment by msolis488** [comment]
Not sure what you mean? Press 'select' + 'start' on the quest controllers? Start seems to be the menu button on the left controller. Couldn't find what 'select' was. Don't think its the Meta button on the right controller.

**Comment by amwatson** [comment]
Press 'select' + 'start' on the gamepad you are trying to use before you press the key you want to bind. It should work after that. 

Its an idiosyncrasy in the way Quest treats gamepads

**Comment by amwatson** [comment]
Going to close assuming this is resolved

**Comment by jtears1** [comment]
Hello, I just downloaded Citra VR a couple of days ago and love it, but the controls for the Quest controllers are uncomfortable, if not unplayable sometimes, making you have to switch to an Xbox or PlayStation controller, which would be alright (I would prefer to play this way anyways), but it takes away from being able to interact with the bottom section unless you always have one of your Oculus remotes on standby to grab and use, which I still feel is an impractical way to play any game, so I guess what I was wanting to ask on here since the other guy didn't really get to was how to change Y from being on the left Oculus remote and B from being on the right Oculus remote to B on the left and Y on the right.
